sudo: false
addons:
  apt:
    packages:
      - check
      - libcppunit-dev
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - pypy
  - pypy3.3-5.2-alpha1
matrix:
  include:
# Travis nightly look to be 3.5.0a4, b3 is out and the error we see
# doesn't happen in trunk.
#    - python: "nightly"
install:
 - pip install -U pip
 - pip install -U wheel setuptools
 - pip install -U .[test,docs]
 - pip list
 - python --version
 - autoreconf -fi && ./configure && make
script:
 - make check
 - make distcheck
 - rst2html.py README.rst README.html
