Import('*')
# describe what we need for C
subunit = SharedLibrary('lib/subunit', ['lib/child.c'])
test_child = Program('tests/test_child.c',
    LIBS=['check', 'subunit'],
    CPPPATH='include',
    LIBPATH='lib')
tests.append(env.TestRC('check', test_child, LIBPATH='lib'))
installs=[]
installs.append(env.Install(lib, subunit))
installs.append(env.Install(include, 'include/subunit/child.h'))
env.Alias('install', installs)
Default(subunit)

