Import('*')
# describe what we need for filters
filters = [
    'subunit-filter',
    'subunit-ls',
    'subunit-stats',
    'subunit-tags',
    'subunit2pyunit',
    'tap2subunit',
    ]
installs = []
for filter in filters:
    installs.append(env.Install(bin, filter))
env.Alias('install', installs)
