#!/usr/bin/env python
#  subunit: extensions to python unittest to get test results from subprocesses.
#  Copyright (C) 2008  Robert Collins <robertc@robertcollins.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

"""List tests in a subunit stream."""

from optparse import OptionParser
import sys
import unittest

from subunit import ProtocolTestCase

class TestIdPrintingResult(unittest.TestResult):

    def __init__(self, stream, show_times=False):
        """Create a FilterResult object outputting to stream."""
        unittest.TestResult.__init__(self)
        self._stream = stream
        self.failed_tests = 0
        self.__time = 0
        self.show_times = show_times
        self._test = None
        self._test_duration = 0
        
    def addError(self, test, err):
        self.failed_tests += 1
        self._test = test

    def addFailure(self, test, err):
        self.failed_tests += 1
        self._test = test

    def addSuccess(self, test):
        self._test = test

    def reportTest(self, test, duration):
        if self.show_times:
            seconds = duration.seconds
            seconds += duration.days * 3600 * 24
            seconds += duration.microseconds / 1000000.0
            self._stream.write(test.id() + ' %0.3f\n' % seconds)
        else:
            self._stream.write(test.id() + '\n')

    def startTest(self, test):
        self._start_time = self._time()

    def stopTest(self, test):
        test_duration = self._time() - self._start_time
        self.reportTest(self._test, test_duration)

    def time(self, time):
        self.__time = time

    def _time(self):
        return self.__time

    def wasSuccessful(self):
        "Tells whether or not this result was a success"
        return self.failed_tests == 0


parser = OptionParser(description=__doc__)
parser.add_option("--times", action="store_true",
    help="list the time each test took (requires a timestamped stream)",
        default=False)
(options, args) = parser.parse_args()
result = TestIdPrintingResult(sys.stdout, options.times)
test = ProtocolTestCase(sys.stdin)
test.run(result)
if result.wasSuccessful():
    exit_code = 0
else:
    exit_code = 1
sys.exit(exit_code)
