#!/usr/bin/env python
#  subunit: extensions to python unittest to get test results from subprocesses.
#  Copyright (C) 2009  Robert Collins <robertc@robertcollins.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

"""Filter a subunit stream to get aggregate statistics."""

from optparse import OptionParser
import sys
import unittest

from subunit import DiscardStream, ProtocolTestCase
try:
    from junitxml import JUnitXmlResult
except ImportError:
    sys.stderr.write("python-junitxml (https://launchpad.net/pyjunitxml or "
        "http://pypi.python.org/pypi/junitxml) is required for this filter.")
    raise

parser = OptionParser(description=__doc__)
parser.add_option("--no-passthrough", action="store_true",
    help="Hide all non subunit input.", default=False, dest="no_passthrough")
parser.add_option("-o", "--output-to",
    help="Output the XML to this path rather than stdout.")
(options, args) = parser.parse_args()
if options.output_to is None:
    output_to = sys.stdout
else:
    output_to = file(options.output_to, 'wb')
try:
    result = JUnitXmlResult(output_to)
    if options.no_passthrough:
        passthrough_stream = DiscardStream()
    else:
        passthrough_stream = None
    test = ProtocolTestCase(sys.stdin, passthrough=passthrough_stream)
    result.startTestRun()
    test.run(result)
    result.stopTestRun()
finally:
    if options.output_to is not None:
        output_to.close()
if result.wasSuccessful():
    exit_code = 0
else:
    exit_code = 1
sys.exit(exit_code)
