#!/usr/bin/env python
#  subunit: extensions to python unittest to get test results from subprocesses.
#  Copyright (C) 2009  Robert Collins <robertc@robertcollins.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

"""Display a subunit stream through python's unittest test runner."""

from optparse import OptionParser
import sys
import unittest

from subunit import DiscardStream, ProtocolTestCase, TestProtocolServer

parser = OptionParser(description=__doc__)
parser.add_option("--no-passthrough", action="store_true",
    help="Hide all non subunit input.", default=False, dest="no_passthrough")
parser.add_option("--progress", action="store_true",
    help="Use bzrlib's test reporter (requires bzrlib)",
        default=False)
(options, args) = parser.parse_args()
if options.no_passthrough:
    passthrough_stream = DiscardStream()
else:
    passthrough_stream = None
test = ProtocolTestCase(sys.stdin, passthrough=passthrough_stream)
if options.progress:
    from bzrlib.tests import TextTestRunner
    from bzrlib import ui
    ui.ui_factory = ui.make_ui_for_terminal(None, sys.stdout, sys.stderr)
    runner = TextTestRunner()
else:
    runner = unittest.TextTestRunner(verbosity=2)
if runner.run(test).wasSuccessful():
    exit_code = 0
else:
    exit_code = 1
sys.exit(exit_code)
